permalink: /:categories/:title
url: "https://yhshanto.github.io/yh.github.io/"
full_name: "YH Shanto"
first_name: "YH"
last_name: "Shanto"
blog_title: "MY Technology Blog"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "pasinduland"
copyright_year: "2017"
google_analytics_code: ""
aboutme: "I am a qulified mobile and web developer"
twitter: "Ghosteyes1"
github: "pasindud"
facebook: "yhshanto"
linkined_url: ""
